allowBuilds:
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - postcss@8.5.10
  - brace-expansion@1.1.16
  - brace-expansion@5.0.7
  - js-yaml@4.3.0
  - sharp@0.35.0
  - next@16.2.11
  - postcss@8.5.12
  - postcss@8.5.18
  - brace-expansion@5.0.8
