name: Formatting Check
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Formatting
        run: npm run format:check
